apiVersion: v1
kind: Pod
metadata:
  name: reverseproxy
spec:
  containers:
  - image: jakazzy123/reverseproxy
    name: reverseproxy
    imagePullPolicy: Always  
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']        
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080